#!/bin/bash

function insert_koompi_repo() {
    if ! awk '/^\s*\[koompi\]/ { in_block = 0 } /^\s*\[koompi\]/ { in_block = 1 } in_block && !/^\s*#/ { found = 1 } END { exit !found }' /etc/pacman.conf; then
        echo -e '\n[koompi]\nSigLevel = Never\nServer = https://dev.koompi.org/koompi\n' | sudo tee -a /etc/pacman.conf >/dev/null 2>&1
    fi
}

insert_koompi_repo
